import { chromium } from 'playwright';
import assert from 'node:assert/strict';
const browser = await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
try {
 const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:5173/',{waitUntil:'networkidle'});
 assert.equal(await page.title(),'phantom');
 assert.equal(await page.locator('.session-label,.palette-status,.design-dock').count(),0);
 assert.equal(await page.locator('.prefix-cells .motion-value[data-value="NaN"]').count(),7);
 const n=page.locator('[data-variable="n"]').locator('.motion-value');
 assert.equal(await n.getAttribute('data-change-count'),null,'No pop on initial render');
 await page.getByRole('button',{name:'Кадр 2',exact:true}).click();
 assert.equal(await page.locator('.editor-line-number.is-active').getAttribute('data-line'),'9');
 assert.equal(await n.textContent(),'6');assert.equal(await n.getAttribute('data-change-count'),'1');
 assert.ok(Number(await n.getAttribute('data-motion-scale'))>1.28,'Changed number expands to its available cell bounds');
 assert.ok(await n.evaluate(el=>el.getAnimations().some(a=>a.effect.getKeyframes().some(k=>Number(String(k.transform).match(/scale\(([^)]+)\)/)?.[1])>1.28))),'Changed number has a measured scale impulse');
 await page.getByRole('button',{name:'Кадр 3',exact:true}).click();assert.equal(await n.getAttribute('data-change-count'),'1','Unchanged value never replays');
 assert.equal(await page.locator('.array-section').first().locator('.motion-value[data-value="0"]').count(),6,'Allocated vector has real zeros');
 await page.getByRole('button',{name:'Кадр 17',exact:true}).click();assert.equal(await page.locator('.prefix-cells .motion-value[data-value="0"]').count(),7);
 await page.getByRole('button',{name:'Кадр 23',exact:true}).click();const value=page.locator('.prefix-cells .array-cell').nth(1).locator('.motion-value');assert.equal(await value.textContent(),'3');
 assert.ok(Number(await value.getAttribute('data-change-count'))>=2);
 await page.getByRole('button',{name:'Кадр 56',exact:true}).click();assert.equal(await page.locator('.has-output').textContent(),'sum = 23\n','cout displays before return');
 await page.getByLabel('Настройки типографики').click();
 await page.getByLabel('Увеличить размер ввода',{exact:true}).click();await page.getByLabel('Увеличить размер вывода',{exact:true}).click();
 await page.getByRole('slider',{name:'Масштаб чисел в дебаггере',exact:true}).fill('1.4');await page.getByRole('slider',{name:'Масштаб названий в дебаггере',exact:true}).fill('1.3');
 assert.equal(await page.getByLabel('Входные данные').evaluate(el=>getComputedStyle(el).fontSize),'15px');
 assert.equal(await page.locator('.has-output').evaluate(el=>getComputedStyle(el).fontSize),'15px');
 assert.equal(await page.locator('.scalar-card strong').first().evaluate(el=>getComputedStyle(el).fontSize),'42px');
 await page.getByRole('tab',{name:'3D и камера',exact:true}).click();await page.getByRole('slider',{name:'Яркость полоски',exact:true}).fill('0.35');
 await page.getByRole('tab',{name:'Сборка',exact:true}).click();assert.equal(await page.locator('[role="tabpanel"] textarea').count(),1);assert.equal(await page.locator('[role="tabpanel"] input,[role="tabpanel"] button').count(),0);
 await page.getByLabel('Закрыть настройки типографики').click();await page.getByLabel('Операций в секунду').selectOption('12');
 await page.locator('#run-button').click();await page.waitForTimeout(600);let progress=await page.locator('.timeline [aria-current="step"]').getAttribute('aria-label');assert.ok(Number(progress.split(' ')[1])>4,'Speed drives live steps');await page.locator('#run-button').click();
 await page.reload();assert.equal(await page.getByLabel('Операций в секунду').inputValue(),'12');
 assert.equal(await page.getByLabel('Входные данные').evaluate(el=>getComputedStyle(el).fontSize),'15px');
 await page.getByRole('button',{name:'Кадр 23',exact:true}).click();await page.waitForTimeout(90);await page.screenshot({path:'previews/phantom-value-motion.png'});
 await page.emulateMedia({reducedMotion:'reduce'});await page.getByRole('button',{name:'Кадр 29',exact:true}).click();
 assert.equal(await page.locator('.motion-value').evaluateAll(els=>els.flatMap(el=>el.getAnimations()).some(a=>a.effect.getKeyframes().some(k=>k.transform))),false,'Reduced motion removes value transforms');
 assert.deepEqual(errors,[]);console.log('PASS: value-change impulses, stable numbers, NaN/zero semantics, declarations/input/output trace, speed, typography and minimal settings.');
} finally {await browser.close()}
