const $ = id => document.getElementById(id);
let artifact = null, session = null, stop = null, busy = false, log = [];
const pretty = value => JSON.stringify(value, null, 2);
function addLog(direction, value) { log.push(`${new Date().toLocaleTimeString()} ${direction}\n${pretty(value)}`); if (log.length > 80) log.shift(); $('log').textContent = log.join('\n\n'); }
async function post(url, payload = {}) { const response = await fetch(url, {method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify(payload)}); const value = await response.json(); addLog('←', value); if (!response.ok || value.ok === false) throw new Error(value.error?.message || `HTTP ${response.status}`); return value; }
function parseLines(text) { return text.split(/\r?\n/).map(x => x.trim()).filter(Boolean); }
function commonSource() { const text = $('source').value; return {id:'source-bundle-1', documents:[{documentId:'main.cpp',revisionId:'source-revision-1',path:'main.cpp',text,sha256:sha256(text)}]}; }
function sha256(text) { // server/backend accepts the exact digest; browser WebCrypto is asynchronous, so use a compact fallback populated on build
  return window.__sha256?.(text) || '0'.repeat(64);
}
async function digest(text) { const bytes = new TextEncoder().encode(text); const hash = await crypto.subtle.digest('SHA-256', bytes); return [...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join(''); }
async function environment() { const out={}; for (const line of parseLines($('environment').value)) { const i=line.indexOf('='); if(i>0) out[line.slice(0,i)] = line.slice(i+1); } return out; }
async function refresh() { const value = await (await fetch('/api/events')).json(); for (const item of value.events) { addLog('event', item); apply(item); } if(value.stderr?.length) $('stderr').textContent = value.stderr.join('\n'); if(value.connected) $('connection').textContent='connected'; if(value.connected) $('connection').classList.add('ok'); }
function apply(frame) { const payload = frame.payload; const result = frame.result; if (payload?.kind === 'state') { $('state').textContent=pretty(payload.state); } if(payload?.kind==='observation') applyObservation(payload.observation); if(result?.kind==='state'){ $('state').textContent=pretty(result.state); if(result.observation) applyObservation(result.observation); } if(result?.kind==='build'){ $('status').textContent=`Build ${result.success?'succeeded':'failed'}: ${result.command?.join(' ')}`; artifact=result.artifact; if(result.stderr) $('stderr').textContent=result.stderr; } if(frame.ok===false) $('status').textContent=`${frame.error.code}: ${frame.error.message}`; }
function applyObservation(o){ stop=o.stop; $('observation').textContent=pretty(o); $('stdout').textContent=o.stdout?.text || '(empty)'; $('stderr').textContent=o.stderr?.text || '(empty)'; }
async function action(kind) { if(busy) return; busy=true; document.querySelectorAll('button[data-action]').forEach(x=>x.disabled=true); try { const sourceText=$('source').value; window.__sha256=await digest(sourceText); let command; if(kind==='build'){ command={kind:'build',source:commonSource(),configuration:{revisionId:'config-revision-1',compiler:'clang++',flags:['-std=c++20','-g','-O0'],outputDirectory:'.phantom/harness-build'},architecture:'x86_64'}; } else if(kind==='launch'){ if(!artifact) throw new Error('Сначала выполните Build'); command={kind:'launch',buildId:artifact.id,input:{id:'input-1',text:$('input').value,encoding:'utf-8',closeAfterWrite:true},argv:parseLines($('argv').value),environment:await environment(),stopAtEntry:true}; } else if(kind==='history'){ command={kind:'listHistory',branchId:stop?.point?.branchId || 'main',afterOrdinal:null,limit:100}; } else if(kind==='state'){ command={kind:'getState'}; } else if(kind==='step'){command={kind:'step',stepKind:'over'};} else command={kind}; const expectedStop = stop || undefined; const value=await post('/api/request',{command,session, ...(expectedStop ? {expectedStop} : {})}); if(value.result?.kind==='launchAccepted') session=value.result.session; if(value.result?.kind==='state'){session=value.session; apply(value);} if(value.result?.kind==='build'){apply(value); artifact=value.result.artifact;} if(value.result?.kind==='observation') applyObservation(value.result.observation); if(value.ok===false) apply(value); await refresh(); $('status').textContent=`${kind}: ${value.ok===false?'error':'accepted'}`; } catch(error){ $('status').textContent=error.message; } finally {busy=false; document.querySelectorAll('button[data-action]').forEach(x=>x.disabled=false);} }
document.querySelectorAll('button[data-action]').forEach(button=>button.addEventListener('click',()=>action(button.dataset.action))); $('reset').addEventListener('click',async()=>{await post('/api/reset'); location.reload();}); setInterval(refresh,500); refresh();
