const $ = id => document.getElementById(id);
let artifact = null, session = null, stop = null, phase = null, busy = false, log = [], eventCursor = 0, refreshing = false;
const pretty = value => JSON.stringify(value, null, 2);
function addLog(direction, value) { log.push(`${new Date().toLocaleTimeString()} ${direction}\n${pretty(value)}`); if (log.length > 80) log.shift(); $('log').textContent = log.join('\n\n'); }
async function post(url, payload = {}) { addLog('→', {endpoint:url, payload}); const response = await fetch(url, {method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify(payload)}); const value = await response.json(); addLog('←', value); if (!response.ok || value.ok === false) throw new Error(value.error?.message || `HTTP ${response.status}`); return value; }
function parseLines(text) { if (!text) return []; return text.replace(/\r\n/g, '\n').split('\n'); }
function commonSource(text, hash) { return {id:'source-bundle-1', documents:[{documentId:'main.cpp',revisionId:'source-revision-1',path:'main.cpp',text,sha256:hash}]}; }
async function digest(text) { const bytes = new TextEncoder().encode(text); const hash = await crypto.subtle.digest('SHA-256', bytes); return [...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join(''); }
async function environment() { const out={}; for (const line of parseLines($('environment').value)) { if (!line) continue; const i=line.indexOf('='); if(i>0) out[line.slice(0,i)] = line.slice(i+1); } return out; }
async function refresh() { if (refreshing) return; refreshing=true; try { const value = await (await fetch(`/api/events?after=${eventCursor}`)).json(); if (value.gap) { addLog('event-gap', {after:eventCursor, nextCursor:value.nextCursor}); $('status').textContent='Some harness events were evicted; refresh the backend state.'; } eventCursor=value.nextCursor ?? eventCursor; for (const item of value.events) { addLog('event', item); apply(item); } if(value.stderr?.length) $('stderr').textContent = value.stderr.join('\n'); if(value.connected) { session=value.session; $('connection').textContent='connected'; $('connection').classList.add('ok'); } else if (session) { session=null; stop=null; phase=null; } refreshControls(); } catch(error) { $('status').textContent=`event polling: ${error.message}`; } finally { refreshing=false; } }
function applyState(state) { phase=state?.phase || null; $('state').textContent=pretty(state); refreshControls(); }
function apply(frame) { const payload = frame.payload; const result = frame.result; if (payload?.kind === 'state') applyState(payload.state); if(payload?.kind==='observation') applyObservation(payload.observation); if(result?.kind==='state'){ session=frame.session || session; applyState(result.state); if(result.observation) applyObservation(result.observation); } if(result?.kind==='build'){ $('status').textContent=`Build ${result.success?'succeeded':'failed'}: ${result.command?.join(' ')}`; artifact=result.artifact; if(result.stderr) $('stderr').textContent=result.stderr; } if(frame.ok===false) $('status').textContent=`${frame.error.code}: ${frame.error.message}`; refreshControls(); }
function applyObservation(o){ stop=o.stop; $('observation').textContent=pretty(o); $('stdout').textContent=o.stdout?.text || '(empty)'; $('stderr').textContent=o.stderr?.text || '(empty)'; refreshControls(); }
function refreshControls() { const canExecute=Boolean(session && stop && phase==='stopped'); const canLaunch=Boolean(artifact && (!session || phase==='terminated' || phase==='failed')); const canSessionRead=Boolean(session); for (const button of document.querySelectorAll('button[data-action]')) { const kind=button.dataset.action; const enabled=kind==='build' || (kind==='launch' ? canLaunch : ['step','continue','pause','stop'].includes(kind) ? canExecute : canSessionRead); button.disabled=busy || !enabled; } }
async function action(kind) { if(busy) return; const liveCommand=['step','continue','pause','stop'].includes(kind); if(liveCommand && !(session && stop && phase==='stopped')) { $('status').textContent='Сначала выполните Launch и дождитесь остановки процесса.'; return; } if(['state','history'].includes(kind) && !session) { $('status').textContent='Сначала выполните Launch.'; return; } busy=true; refreshControls(); try { const sourceText=$('source').value; let command; if(kind==='build'){ command={kind:'build',source:commonSource(sourceText, await digest(sourceText)),configuration:{revisionId:'config-revision-1',compiler:'clang++',flags:['-std=c++20','-g','-O0'],outputDirectory:'.phantom/harness-build'},architecture:'x86_64'}; } else if(kind==='launch'){ if(!artifact) throw new Error('Сначала выполните Build'); command={kind:'launch',buildId:artifact.id,input:{id:'input-1',text:$('input').value,encoding:'utf-8',closeAfterWrite:true},argv:parseLines($('argv').value),environment:await environment(),stopAtEntry:true}; } else if(kind==='history'){ command={kind:'listHistory',branchId:stop?.point?.branchId || 'main',afterOrdinal:null,limit:100}; } else if(kind==='state'){ command={kind:'getState'}; } else if(kind==='step'){command={kind:'step',stepKind:'over'};} else command={kind}; const expectedStop = liveCommand ? stop : undefined; const value=await post('/api/request',{command,session, ...(expectedStop ? {expectedStop} : {})}); if(value.result?.kind==='launchAccepted') { session=value.result.session; phase=null; stop=null; } if(value.result?.kind==='state'){session=value.session; apply(value);} if(value.result?.kind==='build'){apply(value); artifact=value.result.artifact;} if(value.result?.kind==='observation') applyObservation(value.result.observation); if(value.ok===false) apply(value); await refresh(); $('status').textContent=`${kind}: ${value.ok===false?'error':'accepted'}`; } catch(error){ $('status').textContent=error.message; } finally {busy=false; refreshControls();} }
document.querySelectorAll('button[data-action]').forEach(button=>button.addEventListener('click',()=>action(button.dataset.action))); $('reset').addEventListener('click',async()=>{await post('/api/reset'); location.reload();}); setInterval(refresh,500); refresh();
